### ISSUE TITLE
mongodb, mongoose version too old

### ISSUE THREAD

**Issue by Conficlown** [freeCodeCamp/boilerplate-project-urlshortener#17]
Error after upgrading mongodb and mongoose version:
"mongodb": "^2.2.5", 
"mongoose": "^4.5.7",
"body-parser": "^1.15.2"

Even after upgrading to the lastest version as of today
"mongodb": "^3.3.3",
 "mongoose": "^5.7.8",
"body-parser": "^1.19.0"

DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:10098) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:10098) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

This needs to be fixed by adapting the code in server.js boilerplate

**Comment by joaoluizn** [comment]
Hey,

I've Updated the version of these libs with #12.  I saw these warnings when testing, but kept then for another PR that was opened.

I think not only putting the new options but also add  some explanation from the docs.

**Comment by Sky020** [comment]
Regarding the warnings, and the options: Users should be able to understand them, and silence them, by this point, as they were mentioned in one of the [first lessons](https://www.freecodecamp.org/learn/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose). For the best compatibility, the boilerplate should not contain any db connection methods, but should leave it up to the user how they prefer to connect.

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
